name: Build and Test FleetComponentTracker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the app
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test --no-build --configuration Release --logger "console;verbosity=detailed"

      - name: Publish for deployment
        run: dotnet publish -c Release -o publish

      - name: Upload publish folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: FleetComponentTracker-publish
          path: publish
